# Generated by hand for initial schema
import uuid
from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AdditionalFilter',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, max_length=32)),
                ('label', models.CharField(max_length=64)),
                ('emoji', models.CharField(blank=True, max_length=8)),
            ],
            options={'ordering': ['label']},
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='FeatureTag',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, max_length=32)),
                ('label', models.CharField(max_length=64)),
            ],
            options={'ordering': ['label']},
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_tier', models.PositiveSmallIntegerField(default=2)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_filters', models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.additionalfilter')),
                ('district', models.ForeignKey(on_delete=deletion.PROTECT, related_name='restaurants', to='restaurants.district')),
                ('features', models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.featuretag')),
            ],
            options={'ordering': ['-rating', 'name']},
        ),
    ]
